%%{init: {'themeVariables': { 'fontSize': '14px'}}}%%
flowchart TB
  r1[t06_mm01]
  r2[t06_mm02]
  r3[t06_mm03]
  t10[t10_mm51]
  sk1[equation_setup]
  sk2[sign_analysis]
  r1 --> r2
  r1 --> r3
  r2 --> t10
  r3 --> t10
  r2 -.-> sk1
  r3 -.-> sk2
