%%{init: {'themeVariables': { 'fontSize': '13px'}}}%%
flowchart LR
  C[RRF-слияние] --> D[Профильный 
  буст]
  D --> E[Расширение 
  по графу]
  E --> F[MMR]
  F --> G[Топологическая
   сортировка]