---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	call_model(LLM)
	call_tools(Вызов инструментов)
	finalize_section(Финальные преобразования)
	__end__([<p>__end__</p>]):::last
	__start__ --> call_model;
	call_model -.-> call_tools;
	call_model -.-> finalize_section;
	call_tools --> call_model;
	finalize_section --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
